# Generated by Django 5.2.6 on 2025-11-24 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('etiqueta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'etiqueta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('licencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('url_legal', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'licencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaBasura',
            fields=[
                ('zona_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tipo_residuo', models.CharField(max_length=50)),
                ('nivel_contaminacion', models.CharField(blank=True, max_length=7, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Localizador.licencia')),
            ],
            options={
                'db_table': 'zona_basura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('reporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cantidad_residuos_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_reporte', models.DateTimeField(blank=True, null=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Localizador.usuario')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localizador.zonabasura')),
            ],
            options={
                'db_table': 'reporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('imagen_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Localizador.reporte')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Localizador.zonabasura')),
            ],
            options={
                'db_table': 'imagen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaEtiqueta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localizador.etiqueta')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localizador.zonabasura')),
            ],
            options={
                'db_table': 'zona_etiqueta',
                'managed': True,
                'unique_together': {('zona', 'etiqueta')},
            },
        ),
    ]
